import { HadithItem, HadithBookMeta } from '../types';

export const HADITH_BOOKS_DATA: HadithBookMeta[] = [
  {
    id: 'bukhari',
    arabicName: 'الجامع الصحيح للبخاري',
    titles: {
      bn: 'আল জামিউস সহীহ- ইমাম বুখারী রহঃ',
      en: 'Sahih al-Bukhari - Imam Bukhari (RA)',
      ur: 'الجامع الصحيح - امام بخاری رح',
      hi: 'अल जामिउस सहीह - इमाम बुख़ारी रह.',
      id: 'Shahih al-Bukhari - Imam Bukhari',
      tr: 'Sahih-i Buhari - İmam Buhari (r.a.)',
    },
    chaptersCount: 83,
    hadithCount: 7053,
    author: 'Imam Bukhari (RA)',
  },
  {
    id: 'muslim',
    arabicName: 'المسند الصحيح لمسلم',
    titles: {
      bn: 'আল মুসনাদুস সহীহ- ইমাম মুসলিম রহঃ',
      en: 'Sahih Muslim - Imam Muslim (RA)',
      ur: 'المسند الصحيح - امام مسلم رح',
      hi: 'अल मुसनदुस सहीह - इमाम मुस्लिम रह.',
      id: 'Shahih Muslim - Imam Muslim',
      tr: 'Sahih-i Müslim - İmam Müslim (r.a.)',
    },
    chaptersCount: 58,
    hadithCount: 7292,
    author: 'Imam Muslim (RA)',
  },
  {
    id: 'tirmidhi',
    arabicName: 'الجامع الكبير الترمذي',
    titles: {
      bn: 'আল জামিউল কাবীর- ইমাম তিরমিযী রহঃ',
      en: 'Jami` at-Tirmidhi - Imam Tirmidhi (RA)',
      ur: 'الجامع الکبیر - امام ترمذی رح',
      hi: 'अल जामिउल कबीर - इमाम तिरमिज़ी रह.',
      id: 'Jami` at-Tirmidhi - Imam Tirmidhi',
      tr: 'Sünen-i Tirmizi - İmam Tirmizi (r.a.)',
    },
    chaptersCount: 48,
    hadithCount: 3956,
    author: 'Imam Tirmidhi (RA)',
  },
  {
    id: 'abudawud',
    arabicName: 'كتاب السنن للإمام أبي داود',
    titles: {
      bn: 'কিতাবুস সুনান - ইমাম আবু দাউদ রহঃ',
      en: 'Sunan Abi Dawud - Imam Abu Dawud (RA)',
      ur: 'سنن ابی داؤد - امام ابو داؤد رح',
      hi: 'किताबुस सुनन - इमाम अबू दाऊद रह.',
      id: 'Sunan Abu Dawud - Imam Abu Dawud',
      tr: 'Sünen-i Ebu Davud - İmam Ebu Davud (r.a.)',
    },
    chaptersCount: 36,
    hadithCount: 5184,
    author: 'Imam Abu Dawud (RA)',
  },
  {
    id: 'nasai',
    arabicName: 'المجتبى من السنن النسائي',
    titles: {
      bn: 'কিতাবুস সুনান (আলমুজতবা) - ইমাম নাসায়ী রহঃ',
      en: 'Sunan an-Nasa\'i - Imam an-Nasa\'i (RA)',
      ur: 'سنن نسائی - امام نسائی رح',
      hi: 'किताबुस सुनन (अलमुज्तबा) - इमाम नसाई रह.',
      id: 'Sunan an-Nasa\'i - Imam an-Nasa\'i',
      tr: 'Sünen-i Nesai - İmam Nesai (r.a.)',
    },
    chaptersCount: 51,
    hadithCount: 5758,
    author: 'Imam an-Nasa\'i (RA)',
  },
  {
    id: 'ibnmajah',
    arabicName: 'كتاب السنن للإمام ابن ماجة',
    titles: {
      bn: 'কিতাবুস সুনান- ইমাম ইবনে মাজাহ রহঃ',
      en: 'Sunan Ibn Majah - Imam Ibn Majah (RA)',
      ur: 'سنن ابن ماجہ - امام ابن ماجہ رح',
      hi: 'किताबुस सुनन - इमाम इब्ने माजाह रह.',
      id: 'Sunan Ibn Majah - Imam Ibn Majah',
      tr: 'Sünen-i İbn Mace - İmam İbn Mace (r.a.)',
    },
    chaptersCount: 36,
    hadithCount: 4341,
    author: 'Imam Ibn Majah (RA)',
  },
  {
    id: 'malik',
    arabicName: 'كتاب الموطأ للإمام مالك',
    titles: {
      bn: 'আল মুওয়াত্তা - ইমাম মালিক রহঃ',
      en: 'Muwatta Malik - Imam Malik (RA)',
      ur: 'موطا امام مالک - امام مالک رح',
      hi: 'अल मुवत्ता - इमाम मालिक रह.',
      id: 'Muwatta Malik - Imam Malik',
      tr: 'Muvatta - İmam Malik (r.a.)',
    },
    chaptersCount: 61,
    hadithCount: 1889,
    author: 'Imam Malik (RA)',
  },
  {
    id: 'shamail',
    arabicName: 'الشمائل المحمدية للإمام الترمذي',
    titles: {
      bn: 'আশ-শামাইলুল মুহাম্মাদিয়্যাহ- ইমাম তিরমিযী রহঃ',
      en: 'Ash-Shama\'il Al-Muhammadiyya - Imam Tirmidhi (RA)',
      ur: 'الشمائل المحمدية - امام ترمذی رح',
      hi: 'अश-शमाईलुल मुहम्मदिय्या - इमाम तिरमिज़ी रह.',
      id: 'Syama\'il Muhammadiyah - Imam Tirmidhi',
      tr: 'Şemâil-i Muhammediyye - İmam Tirmizi (r.a.)',
    },
    chaptersCount: 2,
    hadithCount: 415,
    author: 'Imam Tirmidhi (RA)',
  },
  {
    id: 'tahawi',
    arabicName: 'شرح معاني الآثار',
    titles: {
      bn: 'শরহু মাআ\'নিল আছার- ইমাম তহাবী রহঃ',
      en: 'Sharh Ma\'ani al-Athar - Imam Tahawi (RA)',
      ur: 'شرح معانی الآثار - امام طحاوی رح',
      hi: 'शरहू मआनिल आछार - इमाम तहावी रह.',
      id: 'Syarah Ma\'ani al-Atsar - Imam Tahawi',
      tr: 'Şerhu Ma\'ânil-Âsâr - İmam Tahavi (r.a.)',
    },
    chaptersCount: 23,
    hadithCount: 7510,
    author: 'Imam Tahawi (RA)',
  },
  {
    id: 'abuhanifa',
    arabicName: 'مسند الإمام الأعظم أبي حنيفة',
    titles: {
      bn: 'মুসনাদে ইমাম আযম আবু হানীফা রহঃ',
      en: 'Musnad Abu Hanifa - Imam Abu Hanifa (RA)',
      ur: 'مسند امام اعظم - امام ابو حنیفہ رح',
      hi: 'मुसनदे इमाम आज़म - इमाम अबू हनीफ़ा रह.',
      id: 'Musnad Imam A\'zam - Imam Abu Hanifa',
      tr: 'Müsned-i Ebu Hanife - İmam Ebu Hanife (r.a.)',
    },
    chaptersCount: 28,
    hadithCount: 523,
    author: 'Imam Abu Hanifa (RA)',
  },
];

export const AUTHENTIC_HADITHS: HadithItem[] = [
  {
    id: 'bukhari_1',
    book: 'Sahih al-Bukhari',
    hadithNumber: '1',
    chapter: 'Revelation & Intentions',
    narrator: 'Umar ibn al-Khattab (RA)',
    arabicText: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى دُنْيَا يُصِيبُهَا أَوْ إِلَى امْرَأَةٍ يَنْكِحُهَا، فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ.',
    englishTranslation: 'The rewards of deeds depend upon the intentions and every person will get the reward according to what he has intended.',
    topic: 'Faith & Tawheed',
    grade: 'Sahih',
    reflection: 'The foundation of all actions in Islam begins in the heart. A pure intention transforms simple daily routines into acts of worship.',
  },
  {
    id: 'muslim_2564',
    book: 'Sahih Muslim',
    hadithNumber: '2564',
    chapter: 'Virtue & Manners',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ.',
    englishTranslation: 'Verily Allah does not look at your outward appearances or your wealth, but rather He looks at your hearts and your deeds.',
    topic: 'Character & Akhlaq',
    grade: 'Sahih',
    reflection: 'Inner spiritual purity and righteous behavior outweigh any superficial worldly status or cosmetic appearance.',
  },
  {
    id: 'bukhari_6407',
    book: 'Sahih al-Bukhari',
    hadithNumber: '6407',
    chapter: 'Remembrance of Allah (Dhikr)',
    narrator: 'Abu Musa al-Ash\'ari (RA)',
    arabicText: 'مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَالَّذِي لاَ يَذْكُرُ رَبَّهُ مَثَلُ الْحَىِّ وَالْمَيِّتِ.',
    englishTranslation: 'The example of the one who remembers his Lord in comparison to the one who does not remember his Lord is like that of the living and the dead.',
    topic: 'Dhikr & Dua',
    grade: 'Sahih',
    reflection: 'Dhikr is the life-breath of the soul. Without constant remembrance of Allah, the heart withers into spiritual lifelessness.',
  },
  {
    id: 'bukhari_6405',
    book: 'Sahih al-Bukhari',
    hadithNumber: '6405',
    chapter: 'Virtues of Tasbeeh',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ.',
    englishTranslation: 'Two phrases are light on the tongue, heavy on the scales of judgment, and deeply beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-Azeem.',
    topic: 'Dhikr & Dua',
    grade: 'Sahih',
    reflection: 'Tremendous divine reward for very brief, consistent invocations throughout the busy hours of your day.',
  },
  {
    id: 'muslim_223',
    book: 'Sahih Muslim',
    hadithNumber: '223',
    chapter: 'Purification & Faith',
    narrator: 'Abu Malik al-Ash\'ari (RA)',
    arabicText: 'الطُّهُورُ شَطْرُ الإِيمَانِ، وَالْحَمْدُ لِلَّهِ تَمْلأُ الْمِيزَانَ، وَسُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ تَمْلآنِ مَا بَيْنَ السَّمَاوَاتِ وَالأَرْضِ، وَالصَّلاَةُ نُورٌ، وَالصَّدَقَةُ بُرْهَانٌ، وَالصَّبْرُ ضِيَاءٌ.',
    englishTranslation: 'Purification is half of faith. Al-hamdu lillah fills the scale. Prayer is a radiant light, charity is proof of faith, and patience is an illuminating brightness.',
    topic: 'Salah & Purification',
    grade: 'Sahih',
    reflection: 'Comprehensive blueprint for the Muslim believer connecting physical purity, prayer, charity, perseverance, and Quranic devotion.',
  },
  {
    id: 'tirmidhi_2003',
    book: 'Jami` at-Tirmidhi',
    hadithNumber: '2003',
    chapter: 'Righteousness & Family',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا، وَخِيَارُكُمْ خِيَارُكُمْ لِنِسَائِهِمْ.',
    englishTranslation: 'The most complete of believers in faith is the one with the best character, and the best of you are those who are best to their wives and families.',
    topic: 'Character & Akhlaq',
    grade: 'Sahih',
    reflection: 'The truest test of religious character is not outward ritualism, but how gentleness, empathy, and honor are displayed inside one\'s home.',
  },
  {
    id: 'bukhari_6011',
    book: 'Sahih al-Bukhari',
    hadithNumber: '6011',
    chapter: 'Good Manners & Mercy',
    narrator: 'An-Nu\'man ibn Bashir (RA)',
    arabicText: 'مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ إِذَا اشْتَكَى مِنْهُ عُضْوٌ تَدَاعَى لَهُ سَائِرُ الْجَسَدِ بِالسَّهَرِ وَالْحُمَّى.',
    englishTranslation: 'The likeness of the believers in their mutual love, mercy, and compassion is that of a single body; when any limb suffers, the entire body responds to it with wakefulness and fever.',
    topic: 'Charity & Kindness',
    grade: 'Sahih',
    reflection: 'Cultivating universal empathy and solidarity with suffering human beings and fellow believers worldwide.',
  },
  {
    id: 'muslim_2699',
    book: 'Sahih Muslim',
    hadithNumber: '2699',
    chapter: 'Seeking Knowledge',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ.',
    englishTranslation: 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise.',
    topic: 'Seeking Knowledge',
    grade: 'Sahih',
    reflection: 'The sacred tranquility and honor that descends upon anyone who strives to seek Islamic knowledge and beneficial wisdom.',
  },
  {
    id: 'bukhari_5641',
    book: 'Sahih al-Bukhari',
    hadithNumber: '5641',
    chapter: 'Patience in Calamities',
    narrator: 'Abu Sa\'id al-Khudri & Abu Hurairah (RA)',
    arabicText: 'مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلاَ وَصَبٍ وَلاَ هَمٍّ وَلاَ حُزْنٍ وَلاَ أَذًى وَلاَ غَمٍّ حَتَّى الشَّوْكَةِ يُشَاكُهَا، إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ.',
    englishTranslation: 'No fatigue, illness, worry, sorrow, harm, or grief afflicts a Muslim—even the prick of a thorn—except that Allah expiates some of his sins by means of it.',
    topic: 'Patience & Trials',
    grade: 'Sahih',
    reflection: 'Even silent hardships, anxiety, and mundane exhaustion become a source of divine purification when borne with patient trust.',
  },
  {
    id: 'tirmidhi_2499',
    book: 'Jami` at-Tirmidhi',
    hadithNumber: '2499',
    chapter: 'Forgiveness & Tawbah',
    narrator: 'Anas ibn Malik (RA)',
    arabicText: 'قَالَ اللَّهُ تَبَارَكَ وَتَعَالَى: يَا ابْنَ آدَمَ إِنَّكَ مَا دَعَوْتَنِي وَرَجَوْتَنِي غَفَرْتُ لَكَ عَلَى مَا كَانَ فِيكَ وَلاَ أُبَالِي...',
    englishTranslation: 'Allah the Almighty declared: "O son of Adam, so long as you call upon Me and ask of Me, I shall forgive you for what you have done."',
    topic: 'Repentance & Mercy',
    grade: 'Sahih',
    reflection: 'The ocean of divine mercy is infinite. Never despair or doubt the readiness of Allah to forgive a genuinely remorseful heart.',
  },
  {
    id: 'abudawud_5090',
    book: 'Sunan Abi Dawud',
    hadithNumber: '5090',
    chapter: 'Manners & Truthfulness',
    narrator: 'Abdullah ibn Mas\'ud (RA)',
    arabicText: 'عَلَيْكُمْ بِالصِّدْقِ، فَإِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ، وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ.',
    englishTranslation: 'Adhere strictly to truthfulness, for truthfulness leads to righteousness, and righteousness leads to Paradise.',
    topic: 'Truthfulness & Honesty',
    grade: 'Sahih',
    reflection: 'Honesty in speech and integrity in action guide a believer safely towards eternal divine pleasure.',
  },
  {
    id: 'nasai_2217',
    book: 'Sunan an-Nasa\'i',
    hadithNumber: '2217',
    chapter: 'Fasting & Worship',
    narrator: 'Abu Umamah (RA)',
    arabicText: 'عَلَيْكَ بِالصَّوْمِ فَإِنَّهُ لاَ عِدْلَ لَهُ.',
    englishTranslation: 'Take to fasting, for there is nothing equivalent to it in spiritual reward.',
    topic: 'Fasting & Devotion',
    grade: 'Sahih',
    reflection: 'Fasting restrains low desires, polishes inner sincerity, and holds an exclusive unmeasured reward from Allah.',
  },
  {
    id: 'ibnmajah_224',
    book: 'Sunan Ibn Majah',
    hadithNumber: '224',
    chapter: 'Sacred Knowledge',
    narrator: 'Anas ibn Malik (RA)',
    arabicText: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ.',
    englishTranslation: 'Seeking knowledge is an obligatory duty upon every Muslim.',
    topic: 'Seeking Knowledge',
    grade: 'Sahih',
    reflection: 'Learning core religious duties and understanding right from wrong is a universal spiritual obligation.',
  },
  {
    id: 'malik_1623',
    book: 'Muwatta Malik',
    hadithNumber: '1623',
    chapter: 'Adherence to Quran & Sunnah',
    narrator: 'Malik ibn Anas (RA)',
    arabicText: 'تَرَكْتُ فِيكُمْ أَمْرَيْنِ لَنْ تَضِلُّوا مَا تَمَسَّكْتُمْ بِهِمَا: كِتَابَ اللَّهِ وَسُنَّةَ نَبِيِّهِ.',
    englishTranslation: 'I have left among you two matters; if you hold fast to them, you will never go astray: the Book of Allah and the Sunnah of His Prophet.',
    topic: 'Faith & Tawheed',
    grade: 'Sahih',
    reflection: 'The Quran and Sunnah remain the unwavering compass of true guidance for all generations until Judgment Day.',
  },
  {
    id: 'shamail_1',
    book: 'Ash-Shama\'il Al-Muhammadiyya',
    hadithNumber: '1',
    chapter: 'Noble Appearance of Prophet ﷺ',
    narrator: 'Anas ibn Malik (RA)',
    arabicText: 'كَانَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ لَيْسَ بِالطَّوِيلِ الْبَائِنِ وَلا بِالْقَصِيرِ، وَلا بِالأَبْيَضِ الأَمْهَقِ وَلا بِالأَدَمِ.',
    englishTranslation: 'The Messenger of Allah ﷺ was neither excessively tall nor short, and his skin was beautifully luminous and middle in tone.',
    topic: 'Character & Akhlaq',
    grade: 'Sahih',
    reflection: 'Contemplating the majestic physical description and serene countenance of our beloved Prophet Muhammad ﷺ.',
  },
  {
    id: 'tahawi_101',
    book: 'Sharh Ma\'ani al-Athar',
    hadithNumber: '101',
    chapter: 'Jurisprudence & Cleanliness',
    narrator: 'Abu Hurairah (RA)',
    arabicText: 'مَا أَنْزَلَ اللَّهُ دَاءً إِلاَّ أَنْزَلَ لَهُ شِفَاءً.',
    englishTranslation: 'Allah has not sent down any disease except that He has also sent down its cure.',
    topic: 'Patience & Trials',
    grade: 'Sahih',
    reflection: 'An inspiring call to hope, medical research, and trusting that Allah provides a cure for every affliction.',
  },
  {
    id: 'abuhanifa_12',
    book: 'Musnad Abu Hanifa',
    hadithNumber: '12',
    chapter: 'Purity of Intent in Worship',
    narrator: 'Alqama (RA)',
    arabicText: 'مَنْ دَعَا إِلَى هُدًى كَانَ لَهُ مِنَ الأَجْرِ مِثْلُ أُجُورِ مَنْ تَبِعَهُ لاَ يَنْقُصُ ذَلِكَ مِنْ أُجُورِهِمْ شَيْئًا.',
    englishTranslation: 'Whoever calls others to guidance will have a reward equal to the rewards of those who follow him, without diminishing their rewards in the slightest.',
    topic: 'Charity & Kindness',
    grade: 'Sahih',
    reflection: 'Guiding a person to a single good deed multiplies your good deeds continuously into ongoing charity.',
  },
];
